dist: trusty
sudo: require
compiler: gcc
language: c
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - cmake
script: make
os:
  - windows
  - osx
  - linux
deploy:
  provider: releases
  api_key: "b1ea91fb09fad3cad7b7bc6cf799eadfa0767904"
  skip_cleanup: true
  file:
  - miner.windows.amd64.exe
  - miner.osx.amd64
  - miner.linux.amd64
  on:
    repo: vfcash/RELEASES
    tags: true
    condition: $LATEST = true
